//! The MCP wire shapes for the tools [`crate::server`] exposes — the
//! argument and result types §6 names, as JSON-schema'd DTOs.
//!
//! # Why these are separate types, not `#[derive(Serialize)]` on the
//! domain types
//!
//! [`BoardRow`], [`IssueSnapshot`] and the [`crate::vcs`] enums they
//! carry are this crate's *internal* vocabulary: `board.rs`'s doc already
//! draws the line that the `board` tool "returns data" while the
//! coordinator agent renders it, and `state/mod.rs` records that its
//! label prefixes are hard-coded pending the workflow parser. Deriving
//! `Serialize`/`JsonSchema` directly on them would publish every one of
//! those internal shapes — field names, enum variant names, and all — as
//! a frozen MCP contract, so a rename inside the crate would silently
//! become a breaking protocol change for every connected agent. The
//! mapping below is the seam where that gets decided on purpose.
//!
//! The schemas are generated by `schemars`, which this crate reaches
//! through `rmcp::schemars` rather than a direct dependency (see
//! `Cargo.toml`) so the derive and the `rmcp` macros can never disagree
//! about a schemars version.

use rmcp::schemars;
use serde::{Deserialize, Serialize};

use crate::board::BoardRow;
use crate::state::{IssueSnapshot, Priority};
use crate::vcs::{
    CiConclusion, IssueRelationships, IssueState, PullRequestState,
    PullRequestStatus,
};

// ---------------------------------------------------------------------
// register (§6 "Registration & lifecycle")
// ---------------------------------------------------------------------

/// Arguments to `register(worker_ref, role, cwd?, spawn_token?)` (§6).
#[derive(Clone, Debug, Deserialize, schemars::JsonSchema)]
pub struct RegisterArgs {
    /// The connecting agent's own reference for itself (§2.6). Recorded
    /// and echoed back; nothing keys off it yet.
    pub worker_ref: String,

    /// The agent's role (§2.6's roster: `coordinator`, `issue-lead`,
    /// `developer`, ...). Deliberately a free-form string, not an enum:
    /// §2.6 calls roles "labels the server keys instructions on" and
    /// says repos "add or drop roles/lenses via config", so a closed set
    /// here would reject a repo-defined role the spec explicitly allows.
    pub role: String,

    /// The directory the client was launched in — required for a
    /// coordinator, which has no `spawn_token` and binds its project
    /// from this path (§2.5, §6). Must be absolute: HTTP/SSE carries no
    /// client working directory, so the server has nothing to resolve a
    /// relative path against.
    #[serde(default)]
    pub cwd: Option<String>,

    /// A spawned phase process's one-time correlation token (§2.6).
    /// **Not implemented in this slice** — supplying one is rejected
    /// rather than ignored; see `src/server/mod.rs`'s module doc for the
    /// full list of what this slice leaves out and why.
    #[serde(default)]
    pub spawn_token: Option<String>,
}

/// What `register` returns once the connection is bound (§6).
#[derive(Clone, Debug, Serialize, schemars::JsonSchema)]
pub struct RegisterResult {
    /// The project handle this connection is now bound to for its life
    /// (§2.5, §15) — `ProjectPointer::name`, set at `init`.
    pub project: String,

    /// That project's GitHub repo slug (`owner/repo`).
    pub repo: String,

    /// That project's container directory (§10.1).
    pub project_dir: String,

    /// The role echoed back, so the client can confirm what the server
    /// recorded.
    pub role: String,

    /// The `worker_ref` echoed back.
    pub worker_ref: String,
}

// ---------------------------------------------------------------------
// board (§6 "Board / status", §13)
// ---------------------------------------------------------------------

/// Arguments to `board(filter?)` (§6, §13).
#[derive(Clone, Debug, Default, Deserialize, schemars::JsonSchema)]
pub struct BoardArgs {
    /// **Unimplemented in this slice.** §6 gives `filter` no shape at
    /// all, and every plausible reading (a label expression, a phase
    /// name, a free-text query) would need a different `gh issue list`
    /// argument or a different post-filter. Accepted so a client passing
    /// one gets a clear rejection instead of silently receiving an
    /// unfiltered board it believes is filtered — see
    /// `src/server/mod.rs`'s module doc.
    #[serde(default)]
    pub filter: Option<String>,
}

/// The orchestration board (§13) for the connection's bound project.
#[derive(Clone, Debug, Serialize, schemars::JsonSchema)]
pub struct BoardResult {
    /// The bound project's handle.
    pub project: String,

    /// The bound project's repo slug.
    pub repo: String,

    /// One row per open issue, ordered by issue number
    /// ([`crate::board::build_board`]).
    pub rows: Vec<BoardRowWire>,

    /// How many open issues the server was willing to page in
    /// ([`crate::BOARD_ISSUE_LIMIT`]).
    pub issue_limit: u32,

    /// Whether the repo had at least `issue_limit` open issues, i.e.
    /// whether this board may be missing rows. Reported rather than left
    /// implicit: §15's "surface, don't bury" makes a silently truncated
    /// board — which reads exactly like a shorter queue — the wrong
    /// failure mode.
    pub truncated: bool,
}

/// One board row (§13) — the wire form of [`BoardRow`].
#[derive(Clone, Debug, Serialize, schemars::JsonSchema)]
pub struct BoardRowWire {
    /// The issue number (scoped to `repo`, §15).
    pub number: u64,
    /// The issue title.
    pub title: String,
    /// The issue's GitHub URL, so the client can render §15's mandatory
    /// clickable `[#N (title)](url)` link without deriving it.
    pub url: String,
    /// Whether the issue is open or closed.
    pub state: IssueStateWire,
    /// The current workflow phase (`status:<phase>`), if labelled.
    pub status: Option<String>,
    /// The issue's priority label, if any.
    pub priority: Option<PriorityWire>,
    /// Phases still gated on a human decision on this issue (§4.3).
    pub gates: Vec<String>,
    /// Phases already approved on this issue (§4.3).
    pub approvals: Vec<String>,
    /// The claiming instance's id (§8.2), if the issue is claimed.
    pub owner: Option<String>,
    /// Dependency/hierarchy edges (§8.4).
    pub relationships: RelationshipsWire,
    /// The most relevant linked pull request's signals, if any.
    pub pull_request: Option<PullRequestStatusWire>,
}

// ---------------------------------------------------------------------
// issue (§6 "Board / status")
// ---------------------------------------------------------------------

/// Arguments to `issue(number)` (§6).
#[derive(Clone, Debug, Deserialize, schemars::JsonSchema)]
pub struct IssueArgs {
    /// The issue number, within the connection's bound project's repo —
    /// §15's "work is identified by `(project, issue_number)`, never a
    /// bare number" is satisfied by the project riding the connection,
    /// which is why there is no `project` argument here.
    pub number: u64,
}

/// One issue's derived state (§4.2, §6) — the wire form of
/// [`IssueSnapshot`].
#[derive(Clone, Debug, Serialize, schemars::JsonSchema)]
pub struct IssueResult {
    /// The bound project's handle.
    pub project: String,
    /// The bound project's repo slug.
    pub repo: String,
    /// The issue number.
    pub number: u64,
    /// The issue title.
    pub title: String,
    /// The issue's GitHub URL (§15).
    pub url: String,
    /// Whether the issue is open or closed.
    pub state: IssueStateWire,
    /// The current workflow phase, if labelled.
    pub status: Option<String>,
    /// The issue's priority label, if any.
    pub priority: Option<PriorityWire>,
    /// Phases still gated on a human decision (§4.3).
    pub gates: Vec<String>,
    /// Phases already approved (§4.3).
    pub approvals: Vec<String>,
    /// The claim on this issue (§8.2), if any.
    pub owner: Option<ClaimWire>,
    /// Dependency/hierarchy edges (§8.4).
    pub relationships: RelationshipsWire,
    /// The most relevant linked pull request's signals, if any.
    pub pull_request: Option<PullRequestStatusWire>,
    /// Every pull request GitHub links to this issue, in the order it
    /// reported them — including the closed ones `pull_request` above
    /// deliberately ranks below open/merged. Normally 0 or 1 (§4.1's
    /// 1:1:1:1 invariant); more than one open PR here is drift (§8.4,
    /// [`crate::state::drift::find_multiple_open_linked_pull_requests`]),
    /// which is why the full list is surfaced rather than collapsed
    /// (§15's "surface, don't bury").
    pub linked_pull_requests: Vec<PullRequestStatusWire>,
}

// ---------------------------------------------------------------------
// Shared leaf shapes
// ---------------------------------------------------------------------

/// A work-claim (§8.2) on the wire.
#[derive(Clone, Debug, Serialize, schemars::JsonSchema)]
pub struct ClaimWire {
    /// The claiming instance's id.
    pub instance: String,
    /// The claim heartbeat's Unix timestamp, in seconds. Staleness
    /// against this is `drift`'s verdict to give (§8.2), not this
    /// tool's — reported raw.
    pub epoch: u64,
}

/// Dependency/hierarchy edges (§8.4) on the wire.
#[derive(Clone, Debug, Default, Serialize, schemars::JsonSchema)]
pub struct RelationshipsWire {
    /// Issues that must merge before this one can enqueue (§8.1).
    pub blocked_by: Vec<u64>,
    /// Issues blocked on this one.
    pub blocking: Vec<u64>,
    /// The parent issue, if this is a sub-issue.
    pub parent: Option<u64>,
    /// This issue's sub-issues, if any.
    pub sub_issues: Vec<u64>,
}

/// A pull request's state/CI/merge-queue signals (§4.2) on the wire.
#[derive(Clone, Copy, Debug, Serialize, schemars::JsonSchema)]
pub struct PullRequestStatusWire {
    /// The pull request number.
    pub number: u64,
    /// Open, closed, or merged.
    pub state: PullRequestStateWire,
    /// The aggregated CI conclusion for its latest commit.
    pub ci: CiConclusionWire,
    /// Whether it currently holds a merge-queue entry (§8.1).
    pub in_merge_queue: bool,
}

/// Whether an issue is open or closed.
#[derive(Clone, Copy, Debug, Serialize, schemars::JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum IssueStateWire {
    /// The issue is open.
    Open,
    /// The issue is closed.
    Closed,
}

/// An issue's priority label (§11.3's shipped `[P0, P1, P2, P3]`).
#[derive(Clone, Copy, Debug, Serialize, schemars::JsonSchema)]
pub enum PriorityWire {
    /// Highest priority.
    P0,
    /// High priority.
    P1,
    /// Normal priority.
    P2,
    /// Low priority.
    P3,
}

/// Whether a pull request is open, closed, or merged.
#[derive(Clone, Copy, Debug, Serialize, schemars::JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum PullRequestStateWire {
    /// The pull request is open.
    Open,
    /// The pull request was closed without merging.
    Closed,
    /// The pull request was merged.
    Merged,
}

/// A pull request's aggregated CI conclusion (§4.2 `signals`).
#[derive(Clone, Copy, Debug, Serialize, schemars::JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum CiConclusionWire {
    /// At least one check is still running, or none have reported yet.
    Pending,
    /// Every reported check succeeded.
    Success,
    /// At least one check failed or errored.
    Failure,
}

// ---------------------------------------------------------------------
// Domain -> wire
// ---------------------------------------------------------------------

impl From<IssueState> for IssueStateWire {
    fn from(state: IssueState) -> IssueStateWire {
        match state {
            IssueState::Open => IssueStateWire::Open,
            IssueState::Closed => IssueStateWire::Closed,
        }
    }
}

impl From<Priority> for PriorityWire {
    fn from(priority: Priority) -> PriorityWire {
        match priority {
            Priority::P0 => PriorityWire::P0,
            Priority::P1 => PriorityWire::P1,
            Priority::P2 => PriorityWire::P2,
            Priority::P3 => PriorityWire::P3,
        }
    }
}

impl From<PullRequestState> for PullRequestStateWire {
    fn from(state: PullRequestState) -> PullRequestStateWire {
        match state {
            PullRequestState::Open => PullRequestStateWire::Open,
            PullRequestState::Closed => PullRequestStateWire::Closed,
            PullRequestState::Merged => PullRequestStateWire::Merged,
        }
    }
}

impl From<CiConclusion> for CiConclusionWire {
    fn from(ci: CiConclusion) -> CiConclusionWire {
        match ci {
            CiConclusion::Pending => CiConclusionWire::Pending,
            CiConclusion::Success => CiConclusionWire::Success,
            CiConclusion::Failure => CiConclusionWire::Failure,
        }
    }
}

impl From<&IssueRelationships> for RelationshipsWire {
    fn from(relationships: &IssueRelationships) -> RelationshipsWire {
        RelationshipsWire {
            blocked_by: relationships.blocked_by.clone(),
            blocking: relationships.blocking.clone(),
            parent: relationships.parent,
            sub_issues: relationships.sub_issues.clone(),
        }
    }
}

impl From<PullRequestStatus> for PullRequestStatusWire {
    fn from(status: PullRequestStatus) -> PullRequestStatusWire {
        PullRequestStatusWire {
            number: status.number,
            state: status.state.into(),
            ci: status.ci.into(),
            in_merge_queue: status.in_merge_queue,
        }
    }
}

impl From<&BoardRow> for BoardRowWire {
    fn from(row: &BoardRow) -> BoardRowWire {
        BoardRowWire {
            number: row.number,
            title: row.title.clone(),
            url: row.url.clone(),
            state: row.state.into(),
            status: row.status.clone(),
            priority: row.priority.map(Into::into),
            gates: row.gates.clone(),
            approvals: row.approvals.clone(),
            owner: row.owner.clone(),
            relationships: (&row.relationships).into(),
            pull_request: row.pull_request.map(Into::into),
        }
    }
}

impl IssueResult {
    /// Project the internal [`IssueSnapshot`] onto the wire, tagging it
    /// with the connection's bound project and the URL §15 requires
    /// every rendered issue reference to carry.
    pub fn from_snapshot(
        snapshot: &IssueSnapshot,
        project: &str,
        repo: &str,
        url: String,
    ) -> IssueResult {
        IssueResult {
            project: project.to_string(),
            repo: repo.to_string(),
            number: snapshot.number,
            title: snapshot.title.clone(),
            url,
            state: snapshot.state.into(),
            status: snapshot.status.clone(),
            priority: snapshot.priority.map(Into::into),
            gates: snapshot.gates.clone(),
            approvals: snapshot.approvals.clone(),
            owner: snapshot.owner.as_ref().map(|claim| ClaimWire {
                instance: claim.instance.clone(),
                epoch: claim.epoch,
            }),
            relationships: (&snapshot.relationships).into(),
            pull_request: snapshot.pull_request.map(Into::into),
            linked_pull_requests: snapshot
                .linked_pull_requests
                .iter()
                .copied()
                .map(Into::into)
                .collect(),
        }
    }
}
