//! The MCP wire shapes for the tools [`crate::server`] exposes — the
//! argument and result types §6 names, as JSON-schema'd DTOs.
//!
//! # Why these are separate types, not `#[derive(Serialize)]` on the
//! domain types
//!
//! [`BoardRow`], [`IssueSnapshot`] and the [`crate::vcs`] enums they
//! carry are this crate's *internal* vocabulary: `board.rs`'s doc already
//! draws the line that the `board` tool "returns data" while the
//! coordinator agent renders it, and `state/mod.rs` records that its
//! label prefixes are hard-coded pending the workflow parser. Deriving
//! `Serialize`/`JsonSchema` directly on them would publish every one of
//! those internal shapes — field names, enum variant names, and all — as
//! a frozen MCP contract, so a rename inside the crate would silently
//! become a breaking protocol change for every connected agent. The
//! mapping below is the seam where that gets decided on purpose.
//!
//! The schemas are generated by `schemars`, which this crate reaches
//! through `rmcp::schemars` rather than a direct dependency (see
//! `Cargo.toml`) so the derive and the `rmcp` macros can never disagree
//! about a schemars version.

use rmcp::schemars;
use serde::{Deserialize, Serialize};

use crate::board::{BacklogRow, BoardRow};
use crate::state::drift::DriftFinding;
use crate::state::{IssueSnapshot, Priority};
use crate::vcs::{
    CiConclusion, IssueRelationships, IssueState, PullRequestState,
    PullRequestStatus,
};
use crate::workflow::{
    AdvanceDecision, ApproveDecision, GateMode, Requirement,
};

use super::logic::{
    AdvanceOutcome, ApproveOutcome, ClaimHolder, DriftReport, SetGateOutcome,
};

// ---------------------------------------------------------------------
// register (§6 "Registration & lifecycle")
// ---------------------------------------------------------------------

/// Arguments to `register(worker_ref, role, cwd?, spawn_token?)` (§6).
#[derive(Clone, Debug, Deserialize, schemars::JsonSchema)]
pub struct RegisterArgs {
    /// The connecting agent's own reference for itself (§2.6). Recorded
    /// and echoed back; nothing keys off it yet.
    pub worker_ref: String,

    /// The agent's role (§2.6's roster: `coordinator`, `issue-lead`,
    /// `developer`, ...). Deliberately a free-form string, not an enum:
    /// §2.6 calls roles "labels the server keys instructions on" and
    /// says repos "add or drop roles/lenses via config", so a closed set
    /// here would reject a repo-defined role the spec explicitly allows.
    pub role: String,

    /// The directory the client was launched in — required for a
    /// coordinator, which has no `spawn_token` and binds its project
    /// from this path (§2.5, §6). Must be absolute: HTTP/SSE carries no
    /// client working directory, so the server has nothing to resolve a
    /// relative path against.
    #[serde(default)]
    pub cwd: Option<String>,

    /// A spawned phase process's one-time correlation token (§2.6).
    /// **Not implemented in this slice** — supplying one is rejected
    /// rather than ignored; see `src/server/mod.rs`'s module doc for the
    /// full list of what this slice leaves out and why.
    #[serde(default)]
    pub spawn_token: Option<String>,
}

/// What `register` returns once the connection is bound (§6).
#[derive(Clone, Debug, Serialize, schemars::JsonSchema)]
pub struct RegisterResult {
    /// The project handle this connection is now bound to for its life
    /// (§2.5, §15) — `ProjectPointer::name`, set at `init`.
    pub project: String,

    /// That project's GitHub repo slug (`owner/repo`).
    pub repo: String,

    /// That project's container directory (§10.1).
    pub project_dir: String,

    /// The role echoed back, so the client can confirm what the server
    /// recorded.
    pub role: String,

    /// The `worker_ref` echoed back.
    pub worker_ref: String,
}

// ---------------------------------------------------------------------
// board (§6 "Board / status", §13)
// ---------------------------------------------------------------------

/// Arguments to `board(filter?)` (§6, §13).
#[derive(Clone, Debug, Default, Deserialize, schemars::JsonSchema)]
pub struct BoardArgs {
    /// **Unimplemented in this slice.** §6 gives `filter` no shape at
    /// all, and every plausible reading (a label expression, a phase
    /// name, a free-text query) would need a different `gh issue list`
    /// argument or a different post-filter. Accepted so a client passing
    /// one gets a clear rejection instead of silently receiving an
    /// unfiltered board it believes is filtered — see
    /// `src/server/mod.rs`'s module doc.
    #[serde(default)]
    pub filter: Option<String>,
}

/// The orchestration board (§13) for the connection's bound project.
#[derive(Clone, Debug, Serialize, schemars::JsonSchema)]
pub struct BoardResult {
    /// The bound project's handle.
    pub project: String,

    /// The bound project's repo slug.
    pub repo: String,

    /// One row per open issue, ordered by issue number
    /// ([`crate::board::build_board`]).
    pub rows: Vec<BoardRowWire>,

    /// How many open issues the server was willing to page in
    /// ([`crate::BOARD_ISSUE_LIMIT`]).
    pub issue_limit: u32,

    /// Whether the repo had at least `issue_limit` open issues, i.e.
    /// whether this board may be missing rows. Reported rather than left
    /// implicit: §15's "surface, don't bury" makes a silently truncated
    /// board — which reads exactly like a shorter queue — the wrong
    /// failure mode.
    pub truncated: bool,
}

/// One board row (§13) — the wire form of [`BoardRow`].
#[derive(Clone, Debug, Serialize, schemars::JsonSchema)]
pub struct BoardRowWire {
    /// The issue number (scoped to `repo`, §15).
    pub number: u64,
    /// The issue title.
    pub title: String,
    /// The issue's GitHub URL, so the client can render §15's mandatory
    /// clickable `[#N (title)](url)` link without deriving it.
    pub url: String,
    /// Whether the issue is open or closed.
    pub state: IssueStateWire,
    /// The current workflow phase (`status:<phase>`), if labelled.
    pub status: Option<String>,
    /// The issue's priority label, if any.
    pub priority: Option<PriorityWire>,
    /// Phases still gated on a human decision on this issue (§4.3).
    pub gates: Vec<String>,
    /// Phases already approved on this issue (§4.3).
    pub approvals: Vec<String>,
    /// The claiming instance's id (§8.2), if the issue is claimed.
    pub owner: Option<String>,
    /// Dependency/hierarchy edges (§8.4).
    pub relationships: RelationshipsWire,
    /// The most relevant linked pull request's signals, if any.
    pub pull_request: Option<PullRequestStatusWire>,
}

// ---------------------------------------------------------------------
// issue (§6 "Board / status")
// ---------------------------------------------------------------------

/// Arguments to `issue(number)` (§6).
#[derive(Clone, Debug, Deserialize, schemars::JsonSchema)]
pub struct IssueArgs {
    /// The issue number, within the connection's bound project's repo —
    /// §15's "work is identified by `(project, issue_number)`, never a
    /// bare number" is satisfied by the project riding the connection,
    /// which is why there is no `project` argument here.
    pub number: u64,
}

/// One issue's derived state (§4.2, §6) — the wire form of
/// [`IssueSnapshot`].
#[derive(Clone, Debug, Serialize, schemars::JsonSchema)]
pub struct IssueResult {
    /// The bound project's handle.
    pub project: String,
    /// The bound project's repo slug.
    pub repo: String,
    /// The issue number.
    pub number: u64,
    /// The issue title.
    pub title: String,
    /// The issue's GitHub URL (§15).
    pub url: String,
    /// Whether the issue is open or closed.
    pub state: IssueStateWire,
    /// The current workflow phase, if labelled.
    pub status: Option<String>,
    /// The issue's priority label, if any.
    pub priority: Option<PriorityWire>,
    /// Phases still gated on a human decision (§4.3).
    pub gates: Vec<String>,
    /// Phases already approved (§4.3).
    pub approvals: Vec<String>,
    /// The claim on this issue (§8.2), if any.
    pub owner: Option<ClaimWire>,
    /// Dependency/hierarchy edges (§8.4).
    pub relationships: RelationshipsWire,
    /// The most relevant linked pull request's signals, if any.
    pub pull_request: Option<PullRequestStatusWire>,
    /// Every pull request GitHub links to this issue, in the order it
    /// reported them — including the closed ones `pull_request` above
    /// deliberately ranks below open/merged. Normally 0 or 1 (§4.1's
    /// 1:1:1:1 invariant); more than one open PR here is drift (§8.4,
    /// [`crate::state::drift::find_multiple_open_linked_pull_requests`]),
    /// which is why the full list is surfaced rather than collapsed
    /// (§15's "surface, don't bury").
    pub linked_pull_requests: Vec<PullRequestStatusWire>,
}

// ---------------------------------------------------------------------
// backlog (§6 "Board / status", §2.7)
// ---------------------------------------------------------------------

/// Arguments to `backlog(filter?)` (§6, §2.7).
#[derive(Clone, Debug, Default, Deserialize, schemars::JsonSchema)]
pub struct BacklogArgs {
    /// **Unimplemented.** §6 gives this argument no shape, exactly as it
    /// gives `board`'s none — and here the plausible readings diverge
    /// even further (a priority floor? a readiness-gap predicate? a
    /// label expression?). Accepted so a client passing one is rejected
    /// rather than silently handed the whole backlog while believing it
    /// asked for a slice of it; see [`BoardArgs::filter`] and
    /// `src/server/mod.rs`'s module doc for the same stance applied to
    /// `board`.
    #[serde(default)]
    pub filter: Option<String>,
}

/// The prioritized not-yet-`ready` worklist (§6, §2.7) for the
/// connection's bound project.
#[derive(Clone, Debug, Serialize, schemars::JsonSchema)]
pub struct BacklogResult {
    /// The bound project's handle.
    pub project: String,

    /// The bound project's repo slug.
    pub repo: String,

    /// One row per open, not-yet-`ready` issue, highest priority first
    /// ([`crate::board::build_backlog`]).
    pub rows: Vec<BacklogRowWire>,

    /// How many open issues the server was willing to page in
    /// ([`crate::BOARD_ISSUE_LIMIT`]) before filtering down to the
    /// not-yet-`ready` ones.
    pub issue_limit: u32,

    /// Whether the repo had at least `issue_limit` **open** issues, i.e.
    /// whether issues that would have belonged on this backlog were
    /// never read at all. Note this is a property of the open-issue read,
    /// not of `rows`: a backlog far shorter than `issue_limit` can still
    /// be truncated. Reported for the same §15 reason `board` reports it,
    /// with more at stake — a silently short backlog reads as "there is
    /// no prepared work left," which is the exact conclusion §2.7's
    /// coordinator acts on.
    pub truncated: bool,
}

/// One backlog row (§6, §2.7) — the wire form of [`BacklogRow`].
#[derive(Clone, Debug, Serialize, schemars::JsonSchema)]
pub struct BacklogRowWire {
    /// The issue number (scoped to `repo`, §15).
    pub number: u64,
    /// The issue title.
    pub title: String,
    /// The issue's GitHub URL, for §15's mandatory clickable
    /// `[#N (title)](url)` rendering.
    pub url: String,
    /// The current workflow phase (`status:<phase>`), or `null` for an
    /// issue that carries no status label yet (§7.2 ph.1).
    pub status: Option<String>,
    /// The issue's priority label, if any — what these rows are ordered
    /// by (§2.7's "surface next by priority").
    pub priority: Option<PriorityWire>,
    /// Phases already approved on this issue (§4.3).
    pub approvals: Vec<String>,
    /// Which approvals this issue still needs to reach `status:ready`
    /// (§7.2 ph.5) — §6's **readiness gap**. Bare approval keys
    /// (`"architecture"`), matching `approvals`' own form.
    ///
    /// An empty list does **not** mean "nothing to do": it usually means
    /// the design package is complete and the issue is waiting only to
    /// be stamped `status:ready` — the highest-value row in this whole
    /// answer for §2.7's queue-filling loop. The one exception is a
    /// `workflow.yaml` edited to remove the `status:ready` seam
    /// entirely, in which case every row's gap reads empty because there
    /// is no bar left to measure against (see
    /// [`crate::board::BacklogRow::readiness_gap`]'s doc).
    pub readiness_gap: Vec<String>,
}

// ---------------------------------------------------------------------
// drift (§6 "Board / status", §12)
// ---------------------------------------------------------------------

/// The drift + contention picture (§6 `drift()`, §12) for the
/// connection's bound project.
#[derive(Clone, Debug, Serialize, schemars::JsonSchema)]
pub struct DriftResult {
    /// The bound project's handle.
    pub project: String,

    /// The bound project's repo slug.
    pub repo: String,

    /// Every drift finding, across all six checks
    /// `crate::state::drift` implements. **Surfaced, never auto-fixed**
    /// (§12, §15) — this is a report, not a plan.
    pub findings: Vec<DriftFindingWire>,

    /// Who currently holds a claim on which issue (§8.2) — the
    /// *contention* half of §6's bullet. Stale claims appear here
    /// **and** in `findings`; see [`ClaimHolderWire::stale`].
    pub claims: Vec<ClaimHolderWire>,

    /// How many open issues the server was willing to page in
    /// ([`crate::BOARD_ISSUE_LIMIT`]).
    pub issue_limit: u32,

    /// Whether the repo had at least `issue_limit` open issues, i.e.
    /// whether drift may exist on issues this scan never read (§15's
    /// "surface, don't bury" — a truncated clean report is not a clean
    /// repo).
    pub truncated: bool,
}

/// One drift finding (§12) — the wire form of [`DriftFinding`].
///
/// Internally tagged on `kind` rather than serialized as serde's default
/// externally-tagged `{"DependencyCycle": {...}}`: a client matching on
/// `finding.kind` needs one stable field to switch on, not a
/// single-key object whose key *is* the discriminant.
#[derive(Clone, Debug, Serialize, schemars::JsonSchema)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum DriftFindingWire {
    /// A `blockedBy` cycle (§8.4).
    DependencyCycle {
        /// The issues in the cycle, in traversal order, rotated to start
        /// at the lowest-numbered issue.
        cycle: Vec<u64>,
    },
    /// An issue blocked on a closed issue (§8.4).
    DependencyOnClosedIssue {
        /// The issue carrying the dependency.
        issue: u64,
        /// The closed issue it depends on.
        depends_on: u64,
    },
    /// An issue blocked on an issue that could not be found (§8.4) —
    /// deleted, transferred, never real, **or** unreadable at scan time;
    /// see `server::logic`'s `read_drift` doc for why this
    /// transport cannot separate the last case from the first three.
    DependencyOnMissingIssue {
        /// The issue carrying the dependency.
        issue: u64,
        /// The issue number it depends on, which could not be found.
        depends_on: u64,
    },
    /// A work-claim whose heartbeat has gone silent past the TTL (§8.2).
    StaleClaim {
        /// The issue whose claim is stale.
        issue: u64,
        /// The instance that held it.
        instance: String,
        /// The claim's last heartbeat, as a Unix timestamp in seconds.
        epoch: u64,
    },
    /// A merged pull request against a still-open issue (§12) — usually
    /// a PR body that never carried `Closes #N`.
    MergedPrWithOpenIssue {
        /// The open issue.
        issue: u64,
        /// The pull request that merged without closing it.
        pull_request: u64,
    },
    /// An issue carrying more than one `status:*` or `owner:*@*` label
    /// (§4.3, §8.2) — the daemon still resolves it deterministically,
    /// but the ambiguity is reported rather than swallowed.
    AmbiguousLabels {
        /// The issue carrying more than one match.
        issue: u64,
        /// The label prefix that matched more than once (`"status:"` or
        /// `"owner:"`).
        prefix: String,
        /// Every matching label, in the order `gh` returned them.
        labels: Vec<String>,
    },
    /// An issue with more than one simultaneously **open** linked pull
    /// request — a §4.1 1:1:1:1 deviation.
    MultipleOpenLinkedPullRequests {
        /// The issue.
        issue: u64,
        /// Every open linked PR's number.
        pull_requests: Vec<u64>,
    },
}

/// One instance's live hold on an issue (§8.2) — the wire form of
/// [`ClaimHolder`].
#[derive(Clone, Debug, Serialize, schemars::JsonSchema)]
pub struct ClaimHolderWire {
    /// The claimed issue.
    pub issue: u64,
    /// The claiming instance's id (`instance_id`, §11.1).
    pub instance: String,
    /// The claim heartbeat's Unix timestamp, in seconds.
    pub epoch: u64,
    /// Whether this claim has lapsed past the configured TTL — the same
    /// verdict the matching [`DriftFindingWire::StaleClaim`] carries,
    /// denormalized onto the claim so a client can render "who holds
    /// what, and is it alive" without joining two lists.
    pub stale: bool,
}

// ---------------------------------------------------------------------
// approve / set_gate (§6 "Approval & gates", §2.3b, §4.3)
// ---------------------------------------------------------------------

/// Arguments to `approve(issue_number, phase, decision, note?)` (§6).
#[derive(Clone, Debug, Deserialize, schemars::JsonSchema)]
pub struct ApproveArgs {
    /// The issue number, within the connection's bound project's repo
    /// (§15 — see [`IssueArgs::number`] for why there is no `project`
    /// argument). Named `issue_number` because §6 names it that in this
    /// tool's signature.
    pub issue_number: u64,

    /// The phase whose gate is being decided — a [`crate::Phase`] id
    /// from the project's own `.spec-flow/workflow.yaml` (§7.0), e.g.
    /// `architecture`. Not the approval label's suffix: the shipped
    /// default's merge gate is the phase `review`, whose approval label
    /// is `approved:merge`. A phase the workflow does not define is
    /// rejected with the list of ids it does.
    pub phase: String,

    /// Grant or deny.
    pub decision: ApproveDecisionWire,

    /// A free-text note recorded with the decision (§6 records it for a
    /// denial in particular). Posted on the issue as part of the
    /// comment this call leaves, so it is durable and visible to every
    /// other instance (§2.3), not just to this connection.
    #[serde(default)]
    pub note: Option<String>,
}

/// Grant or deny, on the wire — the wire form of
/// [`crate::ApproveDecision`].
#[derive(Clone, Copy, Debug, Deserialize, Serialize, schemars::JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum ApproveDecisionWire {
    /// Approve the gate: the phase's approval label is written.
    Grant,
    /// Refuse the gate: no approval label is written, and the decision
    /// (with its note) is recorded as a comment. See
    /// [`ApproveResult::reentry_triggered`].
    Deny,
}

/// What `approve` did, and the issue's state afterwards (§6).
#[derive(Clone, Debug, Serialize, schemars::JsonSchema)]
pub struct ApproveResult {
    /// The decision, echoed back.
    pub decision: ApproveDecisionWire,

    /// The phase id as the workflow spells it.
    pub phase: String,

    /// The approval label written, when one was. `null` for a denial,
    /// and for a grant on a phase that declares no `approval_label` at
    /// all — in which case the comment this call posted is the only
    /// record, and this field being `null` is how a client can tell.
    pub approval_label: Option<String>,

    /// For a denial: the re-entry this workflow defines for the phase
    /// (§6's product-spec→re-groom / architecture→re-propose /
    /// test-plan→re-plan / merge→address), named so a coordinator can
    /// say what still has to happen. `null` for a grant, and for a
    /// denial on a phase whose workflow defines no re-entry.
    pub reentry: Option<String>,

    /// Whether the daemon actually re-ran or spawned that re-entry.
    ///
    /// **Always `false`.** §6's deny contract has two halves — record
    /// the state + note, and route the phase back — and this server
    /// implements the first only: routing means spawning an agent or
    /// re-running a phase, and no phase engine or spawner runs
    /// alongside it (see `src/server/mod.rs`'s module doc). Reported as
    /// a field rather than left to be inferred, so a client cannot read
    /// a populated `reentry` as "the workflow has moved on" (§15's
    /// "surface, don't bury").
    pub reentry_triggered: bool,

    /// The issue, re-read from GitHub after the write — the same shape
    /// `issue(number)` returns, so a client renders it with the same
    /// code. A re-read, not an assumption about what the write
    /// produced (§2.3).
    pub issue: IssueResult,
}

/// Arguments to `set_gate(issue_number, phase, mode)` (§6, §4.3).
#[derive(Clone, Debug, Deserialize, schemars::JsonSchema)]
pub struct SetGateArgs {
    /// The issue number, within the connection's bound project's repo.
    pub issue_number: u64,

    /// The phase whose gate is being set — a [`crate::Phase`] id from
    /// the project's `.spec-flow/workflow.yaml`, exactly as
    /// [`ApproveArgs::phase`].
    pub phase: String,

    /// The gate mode to set for this issue.
    pub mode: GateModeWire,
}

/// A phase's gate mode on the wire (§2.3b) — the wire form of
/// [`crate::GateMode`].
#[derive(Clone, Copy, Debug, Deserialize, Serialize, schemars::JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum GateModeWire {
    /// No approval; the phase advances automatically.
    None,
    /// The server requests approval and waits (§2.3b).
    Human,
    /// The gate is auto-approved.
    Auto,
}

/// What `set_gate` did, and the issue's state afterwards (§6, §4.3).
#[derive(Clone, Debug, Serialize, schemars::JsonSchema)]
pub struct SetGateResult {
    /// The phase id as the workflow spells it.
    pub phase: String,

    /// The mode requested, echoed back.
    pub mode: GateModeWire,

    /// The `gate:<phase>` label this call wrote (§4.3).
    pub label: String,

    /// Whether that label is now present (`human`) or absent (`none`
    /// and `auto` alike). Both permissive modes produce the *same*
    /// absent-label state: the per-issue label scheme is one binary
    /// marker and cannot encode three, so this field reports what was
    /// actually written rather than implying the mode is separately
    /// recorded — see [`crate::set_gate`] for the full reasoning, and
    /// for why the merge gate cannot be silently opened this way.
    pub label_present: bool,

    /// What this phase's gate **actually evaluates to** right now,
    /// after this write — not always the same as `mode`. A merge-gate
    /// phase configured `human` by default ignores a `mode: auto`
    /// request's label removal and stays `human` (§4.3's "merge is
    /// special — never implicit auto"); this field is how a client
    /// tells that apart from `mode`/`label_present` alone, rather than
    /// believing a merge gate opened when it did not (§15's "surface,
    /// don't bury"). See `logic`'s `set_gate_for_issue` doc.
    pub effective_mode: GateModeWire,

    /// The issue, re-read from GitHub after the write — the same shape
    /// `issue(number)` returns.
    pub issue: IssueResult,
}

// ---------------------------------------------------------------------
// advance (§6 "Work", §7.1)
// ---------------------------------------------------------------------

/// Arguments to `advance(issue_number)` (§6).
#[derive(Clone, Debug, Deserialize, schemars::JsonSchema)]
pub struct AdvanceArgs {
    /// The issue number, within the connection's bound project's repo
    /// (§15 — see [`IssueArgs::number`] for why there is no `project`
    /// argument). Named `issue_number` because §6 names it that in this
    /// tool's signature.
    pub issue_number: u64,
}

/// What `advance` decided, what it wrote, and the issue afterwards (§6).
#[derive(Clone, Debug, Serialize, schemars::JsonSchema)]
pub struct AdvanceResult {
    /// Where the state machine says this issue can go next — including
    /// every "it cannot move, and here is precisely why" answer, which
    /// is a normal successful result rather than an error (see
    /// `logic`'s `advance_issue`).
    pub decision: AdvanceDecisionWire,

    /// The `status:<phase>` label this call added to the issue, or
    /// `null` when nothing was written.
    ///
    /// `null` alongside a `decision.kind` of `advance` is a real, if
    /// unusual, case: the target phase declares no `status_label`, so
    /// there was no label to write and the previous one was deliberately
    /// left in place rather than erasing the issue's only GitHub-durable
    /// record of its workflow position (§2.3). See `logic`'s
    /// `advance_issue`.
    pub status_label_added: Option<String>,

    /// The `status:<phase>` label this call removed — the issue's
    /// previous position. `null` when nothing was written, when the
    /// issue carried no status label at all, or when the target phase's
    /// own status label is the one just added.
    pub status_label_removed: Option<String>,

    /// Whether the daemon executed the target phase's action.
    ///
    /// **Always `false`.** An `advance` writes the status-label
    /// transition and nothing else: no agent is spawned for an
    /// agent-action target, no merge is enqueued when the target is the
    /// merge gate, and no `finalize` cleanup runs — no phase engine or
    /// spawner runs alongside this server (see `src/server/mod.rs`'s
    /// module doc). Reported as a field rather than left to be inferred
    /// from a status label that moved, for the same §15 "surface, don't
    /// bury" reason [`ApproveResult::reentry_triggered`] exists.
    pub action_executed: bool,

    /// The issue as GitHub reports it now — the same shape
    /// `issue(number)` returns. A genuine re-read after the write on the
    /// advancing path; on every other path nothing was written, so it is
    /// the read the decision was computed from.
    pub issue: IssueResult,
}

/// One `advance` decision (§6, §7.1) — the wire form of
/// [`AdvanceDecision`].
///
/// Internally tagged on `kind`, exactly as [`DriftFindingWire`] is and
/// for the same reason: a client switches on one stable field rather
/// than on the single key of a `{"BlockedOnGate": {...}}` object.
///
/// Every "blocked" variant is a **successful** answer to §6's question,
/// not an error — see `logic`'s `advance_issue`.
#[derive(Clone, Debug, Serialize, schemars::JsonSchema)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum AdvanceDecisionWire {
    /// The issue carries no `status:<phase>` label, so there is nothing
    /// to advance from. Stamping an initial status is issue creation's
    /// job (§6 `create_issue`), which this server does not implement.
    NoCurrentPhase,

    /// The issue's `status:<phase>` label matches no phase in this
    /// project's `.spec-flow/workflow.yaml` — drift, not a decision the
    /// state machine can make.
    UnknownPhase {
        /// The unrecognized status (the label's suffix, e.g. `triage`).
        status: String,
    },

    /// The current phase is parked on a gate that is not clear (§4.3):
    /// §6's "stops at a `human` gate". Clear it with `approve` (or the
    /// `approved:<phase>` label) and call again.
    BlockedOnGate {
        /// The current phase's id.
        phase: String,
    },

    /// The current phase's own `requires` are not all satisfied (§7.1):
    /// §6's "blocks on unmet `requires`".
    BlockedOnRequires {
        /// The current phase's id.
        phase: String,
        /// Every requirement still unmet, in the order the workflow
        /// declares them.
        unmet: Vec<RequirementWire>,
    },

    /// The current phase is clear, but the **next** phase's own
    /// `requires` are not — checked before entering it, because a
    /// phase's action can run on entry (the shipped default's `review`
    /// phase *is* the merge enqueue). Distinct from
    /// `blocked_on_requires`, which is about the phase the issue is on
    /// now.
    NextPhaseNotReady {
        /// The id of the phase the issue is not yet clear to enter.
        phase: String,
        /// Every one of that phase's requirements still unmet.
        unmet: Vec<RequirementWire>,
    },

    /// The next phase is a mechanical server phase whose own gate is not
    /// clear — checked before entering it, since its action runs on
    /// entry and *is* what the gate exists to hold back (§4.3's "merge
    /// is special", and any per-issue `gate:<phase>` override).
    NextPhaseGateBlocked {
        /// The id of the server phase the issue is not yet clear to
        /// enter.
        phase: String,
    },

    /// The issue advanced. `status_label_added`/`status_label_removed`
    /// report the transition actually written, and `action_executed`
    /// reports that the target phase's action did **not** run.
    Advance {
        /// The id of the phase the issue advanced to.
        to: String,
    },

    /// The issue is on the last phase of the pipeline; there is nothing
    /// further to advance to. (§7.2's out-of-band re-entries are not
    /// part of this linear sequence.)
    Done {
        /// The final phase's id.
        phase: String,
    },
}

/// One unmet phase entry condition (§7.1 `requires`) — the wire form of
/// [`Requirement`].
///
/// Internally tagged on `kind` like its siblings above. The variants
/// carry their payload under a *named* field rather than as a bare
/// string, because the four kinds' payloads are not the same thing: an
/// approval names a phase, `ci`/`roborev` name an expected value, and
/// `unrecognized` carries text this crate could not classify at all.
#[derive(Clone, Debug, Serialize, schemars::JsonSchema)]
#[serde(tag = "kind", rename_all = "snake_case")]
pub enum RequirementWire {
    /// `approved:<phase>` — that phase's approval label must be on the
    /// issue (§4.3).
    Approved {
        /// The bare phase key the approval names (e.g. `architecture`),
        /// matching the form [`IssueResult::approvals`] carries.
        phase: String,
    },

    /// `deps_merged` — every issue this one's `blockedBy` points at must
    /// have merged or closed (§8.4).
    ///
    /// Reported as unmet **also** when a dependency issue could not be
    /// read at all: that failure is treated as "not merged" so an
    /// unverifiable dependency can never clear §8.1's merge gate, and
    /// this shape cannot distinguish the two (the daemon logs which it
    /// was). See `logic`'s `dependencies_satisfied`.
    DepsMerged,

    /// `{ci: <value>}` — the linked pull request's CI conclusion must
    /// equal `expected`. Unmet when there is no linked PR at all.
    Ci {
        /// The value the workflow asks for (`green` in the shipped
        /// default).
        expected: String,
    },

    /// `{roborev: <value>}` — the most recently reported roborev verdict
    /// must equal `expected`.
    ///
    /// **Currently always unmet.** §12 makes roborev a signal an agent
    /// `report`s, and this server implements no `report` tool, so it
    /// holds no verdict to compare against — see `src/server/mod.rs`'s
    /// module doc. On the shipped default this is what keeps an issue
    /// out of `review`.
    Roborev {
        /// The value the workflow asks for (`clean` in the shipped
        /// default).
        expected: String,
    },

    /// A requirement this crate does not interpret (§7.1 names
    /// `status:<phase>` and `lease:<resource>` shapes the shipped
    /// default never uses). Always reported as unmet: a condition the
    /// daemon cannot evaluate must never read as satisfied.
    Unrecognized {
        /// The requirement verbatim, as the workflow file spells it.
        requirement: String,
    },
}

// ---------------------------------------------------------------------
// Shared leaf shapes
// ---------------------------------------------------------------------

/// A work-claim (§8.2) on the wire.
#[derive(Clone, Debug, Serialize, schemars::JsonSchema)]
pub struct ClaimWire {
    /// The claiming instance's id.
    pub instance: String,
    /// The claim heartbeat's Unix timestamp, in seconds. Staleness
    /// against this is `drift`'s verdict to give (§8.2), not this
    /// tool's — reported raw.
    pub epoch: u64,
}

/// Dependency/hierarchy edges (§8.4) on the wire.
#[derive(Clone, Debug, Default, Serialize, schemars::JsonSchema)]
pub struct RelationshipsWire {
    /// Issues that must merge before this one can enqueue (§8.1).
    pub blocked_by: Vec<u64>,
    /// Issues blocked on this one.
    pub blocking: Vec<u64>,
    /// The parent issue, if this is a sub-issue.
    pub parent: Option<u64>,
    /// This issue's sub-issues, if any.
    pub sub_issues: Vec<u64>,
}

/// A pull request's state/CI/merge-queue signals (§4.2) on the wire.
#[derive(Clone, Copy, Debug, Serialize, schemars::JsonSchema)]
pub struct PullRequestStatusWire {
    /// The pull request number.
    pub number: u64,
    /// Open, closed, or merged.
    pub state: PullRequestStateWire,
    /// The aggregated CI conclusion for its latest commit.
    pub ci: CiConclusionWire,
    /// Whether it currently holds a merge-queue entry (§8.1).
    pub in_merge_queue: bool,
}

/// Whether an issue is open or closed.
#[derive(Clone, Copy, Debug, Serialize, schemars::JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum IssueStateWire {
    /// The issue is open.
    Open,
    /// The issue is closed.
    Closed,
}

/// An issue's priority label (§11.3's shipped `[P0, P1, P2, P3]`).
#[derive(Clone, Copy, Debug, Serialize, schemars::JsonSchema)]
pub enum PriorityWire {
    /// Highest priority.
    P0,
    /// High priority.
    P1,
    /// Normal priority.
    P2,
    /// Low priority.
    P3,
}

/// Whether a pull request is open, closed, or merged.
#[derive(Clone, Copy, Debug, Serialize, schemars::JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum PullRequestStateWire {
    /// The pull request is open.
    Open,
    /// The pull request was closed without merging.
    Closed,
    /// The pull request was merged.
    Merged,
}

/// A pull request's aggregated CI conclusion (§4.2 `signals`).
#[derive(Clone, Copy, Debug, Serialize, schemars::JsonSchema)]
#[serde(rename_all = "snake_case")]
pub enum CiConclusionWire {
    /// At least one check is still running, or none have reported yet.
    Pending,
    /// Every reported check succeeded.
    Success,
    /// At least one check failed or errored.
    Failure,
}

// ---------------------------------------------------------------------
// Domain -> wire
// ---------------------------------------------------------------------

impl From<IssueState> for IssueStateWire {
    fn from(state: IssueState) -> IssueStateWire {
        match state {
            IssueState::Open => IssueStateWire::Open,
            IssueState::Closed => IssueStateWire::Closed,
        }
    }
}

impl From<Priority> for PriorityWire {
    fn from(priority: Priority) -> PriorityWire {
        match priority {
            Priority::P0 => PriorityWire::P0,
            Priority::P1 => PriorityWire::P1,
            Priority::P2 => PriorityWire::P2,
            Priority::P3 => PriorityWire::P3,
        }
    }
}

impl From<PullRequestState> for PullRequestStateWire {
    fn from(state: PullRequestState) -> PullRequestStateWire {
        match state {
            PullRequestState::Open => PullRequestStateWire::Open,
            PullRequestState::Closed => PullRequestStateWire::Closed,
            PullRequestState::Merged => PullRequestStateWire::Merged,
        }
    }
}

impl From<CiConclusion> for CiConclusionWire {
    fn from(ci: CiConclusion) -> CiConclusionWire {
        match ci {
            CiConclusion::Pending => CiConclusionWire::Pending,
            CiConclusion::Success => CiConclusionWire::Success,
            CiConclusion::Failure => CiConclusionWire::Failure,
        }
    }
}

impl From<&IssueRelationships> for RelationshipsWire {
    fn from(relationships: &IssueRelationships) -> RelationshipsWire {
        RelationshipsWire {
            blocked_by: relationships.blocked_by.clone(),
            blocking: relationships.blocking.clone(),
            parent: relationships.parent,
            sub_issues: relationships.sub_issues.clone(),
        }
    }
}

impl From<PullRequestStatus> for PullRequestStatusWire {
    fn from(status: PullRequestStatus) -> PullRequestStatusWire {
        PullRequestStatusWire {
            number: status.number,
            state: status.state.into(),
            ci: status.ci.into(),
            in_merge_queue: status.in_merge_queue,
        }
    }
}

impl From<&BoardRow> for BoardRowWire {
    fn from(row: &BoardRow) -> BoardRowWire {
        BoardRowWire {
            number: row.number,
            title: row.title.clone(),
            url: row.url.clone(),
            state: row.state.into(),
            status: row.status.clone(),
            priority: row.priority.map(Into::into),
            gates: row.gates.clone(),
            approvals: row.approvals.clone(),
            owner: row.owner.clone(),
            relationships: (&row.relationships).into(),
            pull_request: row.pull_request.map(Into::into),
        }
    }
}

impl From<&BacklogRow> for BacklogRowWire {
    fn from(row: &BacklogRow) -> BacklogRowWire {
        BacklogRowWire {
            number: row.number,
            title: row.title.clone(),
            url: row.url.clone(),
            status: row.status.clone(),
            priority: row.priority.map(Into::into),
            approvals: row.approvals.clone(),
            readiness_gap: row.readiness_gap.clone(),
        }
    }
}

impl From<&DriftFinding> for DriftFindingWire {
    // Exhaustive on purpose despite `DriftFinding` being
    // `#[non_exhaustive]`: that attribute constrains *other* crates, and
    // this one is the same crate — so a seventh drift kind added to
    // `state::drift` fails to compile here until it is given a wire
    // shape, instead of silently disappearing from every `drift()`
    // answer behind a catch-all arm.
    fn from(finding: &DriftFinding) -> DriftFindingWire {
        match finding {
            DriftFinding::DependencyCycle { cycle } => {
                DriftFindingWire::DependencyCycle { cycle: cycle.clone() }
            }
            DriftFinding::DependencyOnClosedIssue { issue, depends_on } => {
                DriftFindingWire::DependencyOnClosedIssue {
                    issue: *issue,
                    depends_on: *depends_on,
                }
            }
            DriftFinding::DependencyOnMissingIssue { issue, depends_on } => {
                DriftFindingWire::DependencyOnMissingIssue {
                    issue: *issue,
                    depends_on: *depends_on,
                }
            }
            DriftFinding::StaleClaim { issue, instance, epoch } => {
                DriftFindingWire::StaleClaim {
                    issue: *issue,
                    instance: instance.clone(),
                    epoch: *epoch,
                }
            }
            DriftFinding::MergedPrWithOpenIssue { issue, pull_request } => {
                DriftFindingWire::MergedPrWithOpenIssue {
                    issue: *issue,
                    pull_request: *pull_request,
                }
            }
            DriftFinding::AmbiguousLabels { issue, prefix, labels } => {
                DriftFindingWire::AmbiguousLabels {
                    issue: *issue,
                    prefix: (*prefix).to_string(),
                    labels: labels.clone(),
                }
            }
            DriftFinding::MultipleOpenLinkedPullRequests {
                issue,
                pull_requests,
            } => DriftFindingWire::MultipleOpenLinkedPullRequests {
                issue: *issue,
                pull_requests: pull_requests.clone(),
            },
        }
    }
}

impl From<&ClaimHolder> for ClaimHolderWire {
    fn from(holder: &ClaimHolder) -> ClaimHolderWire {
        ClaimHolderWire {
            issue: holder.issue,
            instance: holder.claim.instance.clone(),
            epoch: holder.claim.epoch,
            stale: holder.stale,
        }
    }
}

impl From<ApproveDecisionWire> for ApproveDecision {
    fn from(decision: ApproveDecisionWire) -> ApproveDecision {
        match decision {
            ApproveDecisionWire::Grant => ApproveDecision::Grant,
            ApproveDecisionWire::Deny => ApproveDecision::Deny,
        }
    }
}

impl From<ApproveDecision> for ApproveDecisionWire {
    fn from(decision: ApproveDecision) -> ApproveDecisionWire {
        match decision {
            ApproveDecision::Grant => ApproveDecisionWire::Grant,
            ApproveDecision::Deny => ApproveDecisionWire::Deny,
        }
    }
}

impl From<GateModeWire> for GateMode {
    fn from(mode: GateModeWire) -> GateMode {
        match mode {
            GateModeWire::None => GateMode::None,
            GateModeWire::Human => GateMode::Human,
            GateModeWire::Auto => GateMode::Auto,
        }
    }
}

impl From<GateMode> for GateModeWire {
    fn from(mode: GateMode) -> GateModeWire {
        match mode {
            GateMode::None => GateModeWire::None,
            GateMode::Human => GateModeWire::Human,
            GateMode::Auto => GateModeWire::Auto,
        }
    }
}

impl ApproveResult {
    /// Project an [`ApproveOutcome`] onto the wire, tagging its issue
    /// with the connection's bound project (§2.5).
    ///
    /// `reentry_triggered` is written as a literal `false` here rather
    /// than read off the outcome: nothing in this crate can set it
    /// true, and a field that could only ever be copied from a
    /// hard-coded `false` on the domain type would just move the same
    /// claim one layer down. See its own doc.
    pub fn from_outcome(
        outcome: &ApproveOutcome,
        project: &str,
        repo: &str,
    ) -> ApproveResult {
        ApproveResult {
            decision: outcome.decision.into(),
            phase: outcome.phase.clone(),
            approval_label: outcome.approval_label.clone(),
            reentry: outcome.reentry.clone(),
            reentry_triggered: false,
            issue: IssueResult::from_snapshot(
                &outcome.snapshot,
                project,
                repo,
                outcome.url.clone(),
            ),
        }
    }
}

impl From<&Requirement> for RequirementWire {
    // Exhaustive despite `Requirement` being `#[non_exhaustive]`, for
    // the same reason `DriftFinding`'s mapping above is: that attribute
    // constrains other crates, not this one, so a new requirement kind
    // fails to compile here until it is given a wire shape instead of
    // silently collapsing into a catch-all arm and vanishing from every
    // `unmet` list a client reads.
    fn from(requirement: &Requirement) -> RequirementWire {
        match requirement {
            Requirement::Approved(phase) => {
                RequirementWire::Approved { phase: phase.clone() }
            }
            Requirement::DepsMerged => RequirementWire::DepsMerged,
            Requirement::Ci(expected) => {
                RequirementWire::Ci { expected: expected.clone() }
            }
            Requirement::Roborev(expected) => {
                RequirementWire::Roborev { expected: expected.clone() }
            }
            Requirement::Unrecognized(requirement) => {
                RequirementWire::Unrecognized {
                    requirement: requirement.clone(),
                }
            }
        }
    }
}

impl From<&AdvanceDecision> for AdvanceDecisionWire {
    // Exhaustive on purpose — see [`RequirementWire`]'s mapping above.
    // `AdvanceDecision` is `#[non_exhaustive]` precisely because it
    // expects to grow (its own doc names §7.4's external-review case),
    // and a new decision silently reaching a client as some other
    // decision's shape is the failure this match's lack of a wildcard
    // prevents.
    fn from(decision: &AdvanceDecision) -> AdvanceDecisionWire {
        match decision {
            AdvanceDecision::NoCurrentPhase => {
                AdvanceDecisionWire::NoCurrentPhase
            }
            AdvanceDecision::UnknownPhase { status } => {
                AdvanceDecisionWire::UnknownPhase { status: status.clone() }
            }
            AdvanceDecision::BlockedOnGate { phase } => {
                AdvanceDecisionWire::BlockedOnGate { phase: phase.clone() }
            }
            AdvanceDecision::BlockedOnRequires { phase, unmet } => {
                AdvanceDecisionWire::BlockedOnRequires {
                    phase: phase.clone(),
                    unmet: unmet.iter().map(Into::into).collect(),
                }
            }
            AdvanceDecision::NextPhaseNotReady { phase, unmet } => {
                AdvanceDecisionWire::NextPhaseNotReady {
                    phase: phase.clone(),
                    unmet: unmet.iter().map(Into::into).collect(),
                }
            }
            AdvanceDecision::NextPhaseGateBlocked { phase } => {
                AdvanceDecisionWire::NextPhaseGateBlocked {
                    phase: phase.clone(),
                }
            }
            // Only the phase's *id* crosses the wire, not the whole
            // `Phase` the decision carries: that type is the parsed
            // shape of a team's own `workflow.yaml` (actions, artifact
            // specs, requirement enums), and publishing it here would
            // freeze the config schema as an MCP contract — the exact
            // thing this module's doc exists to prevent. A client that
            // wants the phase's definition reads the file.
            AdvanceDecision::Advance { to } => {
                AdvanceDecisionWire::Advance { to: to.id.clone() }
            }
            AdvanceDecision::Done { phase } => {
                AdvanceDecisionWire::Done { phase: phase.clone() }
            }
        }
    }
}

impl AdvanceResult {
    /// Project an [`AdvanceOutcome`] onto the wire, tagging its issue
    /// with the connection's bound project (§2.5).
    ///
    /// `action_executed` is written as a literal `false` here rather
    /// than read off the outcome, exactly as
    /// [`ApproveResult::reentry_triggered`] is: nothing in this crate
    /// can set it true, and a domain field that could only ever be
    /// copied from a hard-coded `false` would just move the same claim
    /// one layer down. See its own doc.
    pub fn from_outcome(
        outcome: &AdvanceOutcome,
        project: &str,
        repo: &str,
    ) -> AdvanceResult {
        AdvanceResult {
            decision: (&outcome.decision).into(),
            status_label_added: outcome.status_added.clone(),
            status_label_removed: outcome.status_removed.clone(),
            action_executed: false,
            issue: IssueResult::from_snapshot(
                &outcome.snapshot,
                project,
                repo,
                outcome.url.clone(),
            ),
        }
    }
}

impl SetGateResult {
    /// Project a [`SetGateOutcome`] onto the wire, tagging its issue
    /// with the connection's bound project (§2.5).
    pub fn from_outcome(
        outcome: &SetGateOutcome,
        project: &str,
        repo: &str,
    ) -> SetGateResult {
        SetGateResult {
            phase: outcome.phase.clone(),
            mode: outcome.mode.into(),
            label: outcome.label.label.clone(),
            label_present: outcome.label.present,
            effective_mode: outcome.effective_mode.into(),
            issue: IssueResult::from_snapshot(
                &outcome.snapshot,
                project,
                repo,
                outcome.url.clone(),
            ),
        }
    }
}

impl DriftResult {
    /// Project a [`DriftReport`] onto the wire, tagging it with the
    /// connection's bound project (§2.5 — `drift()` takes no `project`
    /// argument because the project rides the connection).
    pub fn from_report(
        report: &DriftReport,
        project: &str,
        repo: &str,
        issue_limit: u32,
    ) -> DriftResult {
        DriftResult {
            project: project.to_string(),
            repo: repo.to_string(),
            findings: report.findings.iter().map(Into::into).collect(),
            claims: report.claims.iter().map(Into::into).collect(),
            issue_limit,
            truncated: report.truncated,
        }
    }
}

impl IssueResult {
    /// Project the internal [`IssueSnapshot`] onto the wire, tagging it
    /// with the connection's bound project and the URL §15 requires
    /// every rendered issue reference to carry.
    pub fn from_snapshot(
        snapshot: &IssueSnapshot,
        project: &str,
        repo: &str,
        url: String,
    ) -> IssueResult {
        IssueResult {
            project: project.to_string(),
            repo: repo.to_string(),
            number: snapshot.number,
            title: snapshot.title.clone(),
            url,
            state: snapshot.state.into(),
            status: snapshot.status.clone(),
            priority: snapshot.priority.map(Into::into),
            gates: snapshot.gates.clone(),
            approvals: snapshot.approvals.clone(),
            owner: snapshot.owner.as_ref().map(|claim| ClaimWire {
                instance: claim.instance.clone(),
                epoch: claim.epoch,
            }),
            relationships: (&snapshot.relationships).into(),
            pull_request: snapshot.pull_request.map(Into::into),
            linked_pull_requests: snapshot
                .linked_pull_requests
                .iter()
                .copied()
                .map(Into::into)
                .collect(),
        }
    }
}
